import Head from "next/head";
import Header from "../../src/component.Header";
import TopBackground from "../../src/component.TopBackground";
import HorizontalSpacer from "../../src/component.HorizontalSpacer";
import Joke from "../../src/component.Joke";
import Settings from "../../src/component.Settings";
import Footer from "../../src/component.Footer";
import randomJokeIdGenerator from "../../utils/randomJokeIdGenerator";
import Link from "next/link";
import { useEffect, useState } from "react";
import ButtonLink from "../../src/component.ButtonLink";

function Jokes({
    joke,
    lowerLimit,
    upperLimit,
    exclude,
}: {
    joke: any;
    lowerLimit: number;
    upperLimit: number;
    exclude: number;
}) {
    const [nextJokeId, setNextJokeId] = useState(0);

    useEffect(() => {
        const nextJokeId = randomJokeIdGenerator(
            lowerLimit,
            upperLimit,
            exclude
        );
        setNextJokeId(nextJokeId);
    }, [exclude]);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <TopBackground />
            <Header />
            <div style={{ margin: "0 32px" }}>
                <HorizontalSpacer space={10} />
                <Joke joke={joke}></Joke>
                <HorizontalSpacer space={8} />
                <Link
                    href={{
                        pathname: "/jokes/[id]",
                    }}
                    as={`/jokes/${nextJokeId}`}
                    passHref
                >
                    <ButtonLink>CRACK ANOTHER ONE</ButtonLink>
                </Link>
                <HorizontalSpacer space={8} />
                <Settings />
            </div>
            <Footer />
        </>
    );
}

export async function getStaticPaths() {
    const res = await fetch("https://v2.jokeapi.dev/info");
    const info = await res.json();
    const englishJokesUpperLimit = 5 || info.jokes.idRange.en[1];
    const jokeIdArray = Array.from(Array(englishJokesUpperLimit).keys());

    const paths = jokeIdArray.map((id) => ({
        params: { id: id.toString() },
    }));

    return { paths, fallback: "blocking" };
}

export async function getStaticProps({ params }: any) {
    const infoResponse = await fetch("https://v2.jokeapi.dev/info");
    const info = await infoResponse.json();
    const [englishJokesLowerLimit, englishJokesUpperLimit] =
        info.jokes.idRange.en;
    const jokeResponse: any = await fetch(
        `https://v2.jokeapi.dev/joke/Any?idRange=${params.id}`
    );
    const joke: any = await jokeResponse.json();

    return {
        props: {
            joke: joke,
            lowerLimit: englishJokesLowerLimit,
            upperLimit: englishJokesUpperLimit,
            exclude: joke.id,
        },
        revalidate: 10,
    };
}

export default Jokes;
