import Head from "next/head";
import Header from "../../src/component.Header";
import TopBackground from "../../src/component.TopBackground";
import HorizontalSpacer from "../../src/component.HorizontalSpacer";
import Joke from "../../src/component.Joke";

function Jokes({ post }: any) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopBackground />
            <Header />
            <HorizontalSpacer space={10} />
            <Joke category={post.category}></Joke>
            {/* <div>{post.joke}</div> */}
        </>
    );
}

export async function getStaticPaths() {
    const res = await fetch("https://v2.jokeapi.dev/info");
    const info = await res.json();
    const englishJokesUpperLimit = 5 || info.jokes.idRange.en[1];
    const jokeIdArray = Array.from(Array(englishJokesUpperLimit).keys());

    const paths = jokeIdArray.map((id) => ({
        params: { id: id.toString() },
    }));

    return { paths, fallback: "blocking" };
}

export async function getStaticProps({ params }: any) {
    const res = await fetch(
        `https://v2.jokeapi.dev/joke/Any?idRange=${params.id}`
    );
    const post = await res.json();

    return { props: { post }, revalidate: 10 };
}

export default Jokes;
